name: Update LOG

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update LOG
        run: |
          echo "Last update: $(date)" > log.txt
          echo "Current time: $(date)" >> log.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add log.txt
          git commit -m "Auto-update log $(date)" || echo "No changes"
          git push
